#!/usr/bin/env python
# coding=utf-8




import oss2
import os
import time
import uuid
import sys
import pyperclip#剪切板库

class UpLoad:
    BucketName = "zy0106picture"
    EndPoint = "oss-cn-beijing.aliyuncs.com"
    Url = [' ']
    def upfile(self,File):
        auth = oss2.Auth('LTAI4FgTns2opyStN6BmtWAQ', 'jJiQ7NU8edRudJtG1dQcsUvwi04m8o')
        bucket = oss2.Bucket(auth, 'http://oss-cn-beijing.aliyuncs.com', 'zy0106picture')
    #获取时间
        Time = time.strftime("%Y.%m.%d-%H-%M")
    #获取ｕｕｉｄ
        Uuid = uuid.uuid4()
        path = Time + '/' +str(Uuid) + '.png' 
        with open(File, 'rb') as fileobj:
            fileobj.seek(0, os.SEEK_SET)
            current = fileobj.tell()
            bucket.put_object(path, fileobj)
    #拼接ｍａｋｄｏｗｎ
        result_str = "![](http://%s.%s/%s)" % (self.BucketName, self.EndPoint, path)
    #由于字符串是不可改变的无法使用＋＝　选用列表凭拼接多个字符串
        self.Url[0] = self.Url[0] + result_str +" "
    #print(Url[0])


    def is_img(self, str):
    #print(str)
        str = str.lower()
        if str in ['.jpg', '.gif', '.png', '.jpeg']:
            return 1
        else:
            return 0


up = UpLoad()
if len(sys.argv) > 1:
    #有参上传
    for i in range(1, len(sys.argv)):
        locFile = sys.argv[i]
        #判断文件是否存在
        if os.path.exists(locFile):
            if up.is_img(os.path.splitext(locFile)[1]):
                #print(locFile)
                up.upfile(locFile)#上传　
            else:
                print("文件非图片")
                exit
            #upfile(locFile)
        else:
            print("文件不存在")
            exit
    #把ｕｒｌ复制到剪切板
    pyperclip.copy(up.Url[0])
    
else: 
    #无参上传
    tmp = pyperclip.paste()
    #print (tmp)
    if up.is_img(os.path.splitext(tmp)[1]):
        up.upfile(tmp); 
        pyperclip.copy(up.Url[0])
    else:
        print("文件非图片")
 
